
package ru.karelin.tmserver.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-03T14:57:35.762+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "PermissionException", targetNamespace = "http://endpoint.tmserver.karelin.ru/")
public class PermissionException_Exception extends Exception {

    private ru.karelin.tmserver.endpoint.PermissionException permissionException;

    public PermissionException_Exception() {
        super();
    }

    public PermissionException_Exception(String message) {
        super(message);
    }

    public PermissionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PermissionException_Exception(String message, ru.karelin.tmserver.endpoint.PermissionException permissionException) {
        super(message);
        this.permissionException = permissionException;
    }

    public PermissionException_Exception(String message, ru.karelin.tmserver.endpoint.PermissionException permissionException, java.lang.Throwable cause) {
        super(message, cause);
        this.permissionException = permissionException;
    }

    public ru.karelin.tmserver.endpoint.PermissionException getFaultInfo() {
        return this.permissionException;
    }
}
