package ru.karelin.tmserver.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-03-29T16:06:54.102+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tmserver.karelin.ru/", name = "TaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getSortedTaskListRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getSortedTaskListResponse")
    @RequestWrapper(localName = "getSortedTaskList", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetSortedTaskList")
    @ResponseWrapper(localName = "getSortedTaskListResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetSortedTaskListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.karelin.tmserver.endpoint.Task> getSortedTaskList(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "sortField", targetNamespace = "")
        java.lang.String sortField,
        @WebParam(name = "isOrderStraight", targetNamespace = "")
        boolean isOrderStraight
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListResponse")
    @RequestWrapper(localName = "getTaskList", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskList")
    @ResponseWrapper(localName = "getTaskListResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.karelin.tmserver.endpoint.Task> getTaskList(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/createTaskRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/createTaskResponse")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.CreateTaskResponse")
    public void createTask(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskName", targetNamespace = "")
        java.lang.String taskName,
        @WebParam(name = "taskDescription", targetNamespace = "")
        java.lang.String taskDescription,
        @WebParam(name = "taskStartDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar taskStartDate,
        @WebParam(name = "taskFinishDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar taskFinishDate,
        @WebParam(name = "taskProjectId", targetNamespace = "")
        java.lang.String taskProjectId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getSortedTaskListByProjectIdRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getSortedTaskListByProjectIdResponse")
    @RequestWrapper(localName = "getSortedTaskListByProjectId", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetSortedTaskListByProjectId")
    @ResponseWrapper(localName = "getSortedTaskListByProjectIdResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetSortedTaskListByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.karelin.tmserver.endpoint.Task> getSortedTaskListByProjectId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "tasksProjectId", targetNamespace = "")
        java.lang.String tasksProjectId,
        @WebParam(name = "sortField", targetNamespace = "")
        java.lang.String sortField,
        @WebParam(name = "isOrderStraight", targetNamespace = "")
        boolean isOrderStraight
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskResponse")
    @RequestWrapper(localName = "getTask", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTask")
    @ResponseWrapper(localName = "getTaskResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.karelin.tmserver.endpoint.Task getTask(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/checkTaskIdRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/checkTaskIdResponse")
    @RequestWrapper(localName = "checkTaskId", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.CheckTaskId")
    @ResponseWrapper(localName = "checkTaskIdResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.CheckTaskIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean checkTaskId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/removeTaskRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/removeTaskResponse")
    @RequestWrapper(localName = "removeTask", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.RemoveTask")
    @ResponseWrapper(localName = "removeTaskResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.RemoveTaskResponse")
    public void removeTask(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/editTaskRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/editTaskResponse")
    @RequestWrapper(localName = "editTask", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.EditTask")
    @ResponseWrapper(localName = "editTaskResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.EditTaskResponse")
    public void editTask(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId,
        @WebParam(name = "taskName", targetNamespace = "")
        java.lang.String taskName,
        @WebParam(name = "taskDescription", targetNamespace = "")
        java.lang.String taskDescription,
        @WebParam(name = "taskStartDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar taskStartDate,
        @WebParam(name = "taskFinishDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar taskFinishDate,
        @WebParam(name = "taskProjectId", targetNamespace = "")
        java.lang.String taskProjectId,
        @WebParam(name = "taskStatus", targetNamespace = "")
        ru.karelin.tmserver.endpoint.Status taskStatus
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListByProjectIdRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListByProjectIdResponse")
    @RequestWrapper(localName = "getTaskListByProjectId", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskListByProjectId")
    @ResponseWrapper(localName = "getTaskListByProjectIdResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskListByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.karelin.tmserver.endpoint.Task> getTaskListByProjectId(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    );

    @WebMethod
    @Action(input = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListByKeywordRequest", output = "http://endpoint.tmserver.karelin.ru/TaskEndpoint/getTaskListByKeywordResponse")
    @RequestWrapper(localName = "getTaskListByKeyword", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskListByKeyword")
    @ResponseWrapper(localName = "getTaskListByKeywordResponse", targetNamespace = "http://endpoint.tmserver.karelin.ru/", className = "ru.karelin.tmserver.endpoint.GetTaskListByKeywordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.karelin.tmserver.endpoint.Task> getTaskListByKeyword(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "searchString", targetNamespace = "")
        java.lang.String searchString
    );
}
